sudo: required

language: java

services:
  - docker

script:
  - docker build --tag whisper_reactnative .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag whisper_reactnative $DOCKER_USERNAME/whisper_reactnative
  - docker push $DOCKER_USERNAME/whisper_reactnative
