sudo: required

language: java

services:
  - docker

before_install:
  - docker build --tag whisper_reactnative .
  - docker run -idt --privileged -w `pwd` -v `pwd`:`pwd` --name whisper_reactnative whisper_reactnative

script:
  - ls -l
  - docker exec whisper_reactnative ls -l
