sudo: required

language: java

services:
  - docker

script:
  - docker build --tag whisper_reactnative:android.latest -f android.dockerfile .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag whisper_reactnative:android.latest $DOCKER_USERNAME/whisper_reactnative:android.latest
  - docker push $DOCKER_USERNAME/whisper_reactnative:android.latest
