sudo: required

os: osx

osx_image: xcode9.1

language: java

install:
  - npm install -g react-native-cli
  - npm update
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - npm test
  - npm run flow
  - cd ios && xcodebuild -project whisper_reactnative.xcodeproj -scheme whisper_reactnative -sdk iphonesimulator11.1 clean test
  - cd ios && xcodebuild -project whisper_reactnative.xcodeproj -scheme whisper_reactnative -sdk iphonesimulator11.1 clean analyze
