sudo: required

language: java

services:
  - docker

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build --tag whisper_reactnative .

deploy:
  - docker tag whisper_reactnative $DOCKER_USERNAME/whisper_reactnative
  - docker push $DOCKER_USERNAME/whisper_reactnative
