sudo: required

env:
  global:
    - DOCKER_CACHE_FILE=${HOME}/docker/cache.tar.gz

language: java

services:
  - docker

before_script:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

script:
  - docker build --tag whisper_reactnative .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag whisper_reactnative $DOCKER_USERNAME/whisper_reactnative
  - docker push $DOCKER_USERNAME/whisper_reactnative

after_script:
  - mkdir -p $(dirname ${DOCKER_CACHE_FILE})
  - docker save $(docker history -q $DOCKER_USERNAME/whisper_reactnative | grep -v '<missing>') | gzip -v -9 > ${DOCKER_CACHE_FILE}
