sudo: required

language: java

services:
  - docker

before_install:
  - docker build --tag whisper_reactnative .
  - docker run -idt --privileged -w `pwd` -v `pwd`:`pwd` --name whisper_reactnative whisper_reactnative

install:
  - docker exec whisper_reactnative npm update

script:
  - docker exec whisper_reactnative sh -c "npm test"
  - docker exec whisper_reactnative sh -c "npm run flow"
  - docker exec whisper_reactnative sh -c "cd android && ./gradlew testDebugUnitTest"
